//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: i2enetworkmessagedefinitions/MobileDevice/CameraScreenMessage.proto
namespace NetworkMessages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CameraScreenMessage")]
  public partial class CameraScreenMessage : global::ProtoBuf.IExtensible
  {
    public CameraScreenMessage() {}
    
    private byte[] _cameraFrame;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cameraFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] cameraFrame
    {
      get { return _cameraFrame; }
      set { _cameraFrame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}