//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: InitializeConnectionMessage.proto
// Note: requires additional types generated from: Remote.proto
namespace NetworkMessages.AuthorativeServer
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitializeConnectionMessage")]
  public partial class InitializeConnectionMessage : global::ProtoBuf.IExtensible
  {
    public InitializeConnectionMessage() {}
    
    private byte[] _SenderID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SenderID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] SenderID
    {
      get { return _SenderID; }
      set { _SenderID = value; }
    }
    private byte[] _SenderSecret;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SenderSecret", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] SenderSecret
    {
      get { return _SenderSecret; }
      set { _SenderSecret = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private readonly global::System.Collections.Generic.List<NetworkMessages.AuthorativeServer.Remote> _AllConnectedRemotes = new global::System.Collections.Generic.List<NetworkMessages.AuthorativeServer.Remote>();
    [global::ProtoBuf.ProtoMember(1, Name=@"AllConnectedRemotes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NetworkMessages.AuthorativeServer.Remote> AllConnectedRemotes
    {
      get { return _AllConnectedRemotes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}