//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Assets/i2eNetworkMessagesDefinitions/AuthorativeServer/Remote.proto
namespace NetworkMessages.AuthorativeServer
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Remote")]
  public partial class Remote : global::ProtoBuf.IExtensible
  {
    public Remote() {}
    
    private byte[] _SenderID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SenderID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] SenderID
    {
      get { return _SenderID; }
      set { _SenderID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}