//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: i2enetworkmessagedefinitions/MobileDevice/SetCameraFieldOfViewMessage.proto
namespace NetworkMessages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetCameraFieldOfViewMessage")]
  public partial class SetCameraFieldOfViewMessage : global::ProtoBuf.IExtensible
  {
    public SetCameraFieldOfViewMessage() {}
    
    private float _fieldOfView;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fieldOfView", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float fieldOfView
    {
      get { return _fieldOfView; }
      set { _fieldOfView = value; }
    }
    private long _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}