//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: i2enetworkmessagedefinitions/MobileDevice/SetCameraResolutionMessage.proto
namespace NetworkMessages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetCameraResolutionMessage")]
  public partial class SetCameraResolutionMessage : global::ProtoBuf.IExtensible
  {
    public SetCameraResolutionMessage() {}
    
    private int _width;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }
    private int _height;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private long _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}