//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: i2enetworkmessagedefinitions/SOA/SOARegisterService.proto
namespace NetworkMessages.SOA
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SOARegisterService")]
  public partial class SOARegisterService : global::ProtoBuf.IExtensible
  {
    public SOARegisterService() {}
    
    private string _serviceName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serviceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serviceName
    {
      get { return _serviceName; }
      set { _serviceName = value; }
    }
    private string _ipv4Address = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ipv4Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipv4Address
    {
      get { return _ipv4Address; }
      set { _ipv4Address = value; }
    }
    private string _ipv6Address = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ipv6Address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipv6Address
    {
      get { return _ipv6Address; }
      set { _ipv6Address = value; }
    }
    private int _port = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private NetworkMessages.SOA.SOARegisterService.Protocol _protocol = NetworkMessages.SOA.SOARegisterService.Protocol.TCP;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(NetworkMessages.SOA.SOARegisterService.Protocol.TCP)]
    public NetworkMessages.SOA.SOARegisterService.Protocol protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Protocol")]
    public enum Protocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP", Value=0)]
      TCP = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP", Value=1)]
      UDP = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}