//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserInitMessage.proto
namespace NetworkMessages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInitMessage")]
  public partial class UserInitMessage : global::ProtoBuf.IExtensible
  {
    public UserInitMessage() {}
    
    private long _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _bodyPartId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bodyPartId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> bodyPartId
    {
      get { return _bodyPartId; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _bodyPartLength = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(3, Name=@"bodyPartLength", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> bodyPartLength
    {
      get { return _bodyPartLength; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _bodyPartPositionX = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(4, Name=@"bodyPartPositionX", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> bodyPartPositionX
    {
      get { return _bodyPartPositionX; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _bodyPartPositionY = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(5, Name=@"bodyPartPositionY", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> bodyPartPositionY
    {
      get { return _bodyPartPositionY; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _bodyPartPositionZ = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(6, Name=@"bodyPartPositionZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> bodyPartPositionZ
    {
      get { return _bodyPartPositionZ; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _bodyPartRotationX = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(7, Name=@"bodyPartRotationX", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> bodyPartRotationX
    {
      get { return _bodyPartRotationX; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _bodyPartRotationY = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(8, Name=@"bodyPartRotationY", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> bodyPartRotationY
    {
      get { return _bodyPartRotationY; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _bodyPartRotationZ = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(9, Name=@"bodyPartRotationZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> bodyPartRotationZ
    {
      get { return _bodyPartRotationZ; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}