//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Implode.proto
namespace NetworkMessages.GestureRecognition.UserCommands
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Implode")]
  public partial class Implode : global::ProtoBuf.IExtensible
  {
    public Implode() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}