//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ObjectNew.proto
namespace NetworkMessages.ObjectTracking
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectNew")]
  public partial class ObjectNew : global::ProtoBuf.IExtensible
  {
    public ObjectNew() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _pos_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private float _pos_z;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private float _rot_x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rot_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rot_x
    {
      get { return _rot_x; }
      set { _rot_x = value; }
    }
    private float _rot_y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rot_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rot_y
    {
      get { return _rot_y; }
      set { _rot_y = value; }
    }
    private float _rot_z;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"rot_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rot_z
    {
      get { return _rot_z; }
      set { _rot_z = value; }
    }
    private int _object_type;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"object_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int object_type
    {
      get { return _object_type; }
      set { _object_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}