//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RequestConnectionEncryptionMessage.proto
namespace NetworkMessages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestConnectionEncryptionMessage")]
  public partial class RequestConnectionEncryptionMessage : global::ProtoBuf.IExtensible
  {
    public RequestConnectionEncryptionMessage() {}
    
    private byte[] _publicKey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"publicKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] publicKey
    {
      get { return _publicKey; }
      set { _publicKey = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private byte[] _sharedSecret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sharedSecret", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] sharedSecret
    {
      get { return _sharedSecret; }
      set { _sharedSecret = value; }
    }
    private byte[] _initializationVector;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"initializationVector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] initializationVector
    {
      get { return _initializationVector; }
      set { _initializationVector = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}