//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ScaleAndRotate.proto
namespace NetworkMessages.GestureRecognition.UserCommands
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScaleAndRotate")]
  public partial class ScaleAndRotate : global::ProtoBuf.IExtensible
  {
    public ScaleAndRotate() {}
    
    private float _x_rotation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x_rotation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x_rotation
    {
      get { return _x_rotation; }
      set { _x_rotation = value; }
    }
    private float _y_rotation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y_rotation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y_rotation
    {
      get { return _y_rotation; }
      set { _y_rotation = value; }
    }
    private float _z_rotation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"z_rotation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z_rotation
    {
      get { return _z_rotation; }
      set { _z_rotation = value; }
    }
    private float _x_scale;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"x_scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x_scale
    {
      get { return _x_scale; }
      set { _x_scale = value; }
    }
    private float _y_scale;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"y_scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y_scale
    {
      get { return _y_scale; }
      set { _y_scale = value; }
    }
    private float _z_scale;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"z_scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z_scale
    {
      get { return _z_scale; }
      set { _z_scale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}